version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  apt_packages:
    - gfortran
    - libopenblas-dev
  jobs:
    post_create_environment:
      - cp -a locale scientific-python-lectures/

submodules:
  include:
    - scientific-python-lectures
  recursive: true

sphinx:
  configuration: scientific-python-lectures/conf.py

python:
  install:
    - requirements: requirements.txt
