version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

submodules:
  include:
    - scientific-python-lectures
  recursive: true

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
