version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  apt_packages:
    - gfortran
    - libopenblas-dev
  commands:
    - pip install -r requirements.txt
    - cp -a locales scientific-python-lectures/
    # Download scikit-learn datasets before sphinx-gallery runs
    - python download_datasets.py
    # Set environment variable for scikit-learn to use cached data
    - export SCIKIT_LEARN_DATA=$PWD/scikit_learn_data
    - python -m sphinx -T -b html -d _build/doctrees -D language=ja scientific-python-lectures $READTHEDOCS_OUTPUT/html

submodules:
  include:
    - scientific-python-lectures
  recursive: true

sphinx:
  configuration: scientific-python-lectures/conf.py
