---
build:
  apt_packages:
    - gfortran
    - libopenblas-dev
  jobs:
    post_create_environment:
      - cp -a locales scientific-python-lectures/
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
python:
  install:
    - requirements: requirements.txt
sphinx:
  configuration: scientific-python-lectures/conf.py
submodules:
  include:
    - scientific-python-lectures
  recursive: true
version: 2
...
