version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  apt_packages:
    - gfortran
    - libopenblas-dev
  jobs:
    post_create_environment:
      - cp -a locales scientific-python-lectures/
    post_install:
      # Download scikit-learn datasets before sphinx-gallery runs
      - python download_datasets.py
  commands:
    # Set environment variable for scikit-learn to use cached data
    - export SCIKIT_LEARN_DATA=$PWD/scikit_learn_data
    - python -m sphinx -T -b html -d _build/doctrees -D language=ja scientific-python-lectures $READTHEDOCS_OUTPUT/html

submodules:
  include:
    - scientific-python-lectures
  recursive: true

sphinx:
  configuration: scientific-python-lectures/conf.py

python:
  install:
    - requirements: requirements.txt
