---
extends: default
rules:
  anchors: enable
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  colons: enable
  commas: enable
  comments:
    ignore-shebangs: true
    min-spaces-from-content: 1
    require-starting-space: true
  comments-indentation: enable
  document-end: enable
  document-start: enable
  empty-lines: enable
  empty-values: enable
  float-values: enable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: enable
  line-length:
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
    max: 130
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings:
    check-keys: true
    required: only-when-needed
  trailing-spaces: enable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
...
