[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64"]

[project]
dependencies = ["docutils"]
description = "Local Sphinx extensions for the scientific-python-lectures translations"
name = "scientific-python-lectures-translations"
requires-python = ">=3.9"
version = "1.0"

[tool.setuptools.packages.find]
where = ["src"]
