name: Dependency Submission

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Submit Dependencies
        uses: actions/dependency-submission-action@v4
        with:
          pip-requirements-path: requirements.txt
